version: "3.8"

services:
  # web:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - test_db

  db:
    image: postgres:latest
    ports: 
      - "5434:5432"
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_db

  test_db:
    image: postgres:latest
    ports: 
      - "6434:5432"
    restart: always
    environment:
      - POSTGRES_USER=test_username
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_local_db


