"""empty message

Revision ID: 1b2d27e7597c
Revises: 947117f9b55f
Create Date: 2025-08-31 23:18:49.424348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b2d27e7597c"
down_revision: Union[str, Sequence[str], None] = "947117f9b55f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_accounts", "company_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_column("user_meeting_relations", "updated_on")
    op.drop_column("user_meeting_relations", "id")
    op.drop_column("user_meeting_relations", "created")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_meeting_relations",
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user_meeting_relations",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_meeting_relations",
        sa.Column(
            "updated_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "user_accounts", "company_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
