"""empty message

Revision ID: 3a8aba67f79c
Revises: 1b2d27e7597c
Create Date: 2025-09-01 23:00:53.333301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8aba67f79c'
down_revision: Union[str, Sequence[str], None] = '1b2d27e7597c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tokens_user_id_key'), 'tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tokens_user_id_key'), 'tokens', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
