"""empty message

Revision ID: 7231777fc402
Revises: 91ce8cc6bac3
Create Date: 2025-10-18 20:00:33.350564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7231777fc402"
down_revision: Union[str, Sequence[str], None] = "91ce8cc6bac3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("author_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "tasks", "user_accounts", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "author_id")
    # ### end Alembic commands ###
