"""empty message

Revision ID: 79850dffe45c
Revises: e897b7dcd5e1
Create Date: 2025-08-31 22:49:06.898195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79850dffe45c"
down_revision: Union[str, Sequence[str], None] = "e897b7dcd5e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("from_user_id", sa.Uuid(), nullable=False))
    op.add_column("comments", sa.Column("to_user_id", sa.Uuid(), nullable=False))
    op.alter_column("comments", "text", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint(op.f("comments_to_user_fkey"), "comments", type_="foreignkey")
    op.drop_constraint(op.f("comments_task_id_fkey"), "comments", type_="foreignkey")
    op.drop_constraint(op.f("comments_from_user_fkey"), "comments", type_="foreignkey")
    op.create_foreign_key(None, "comments", "user_accounts", ["to_user_id"], ["id"])
    op.create_foreign_key(None, "comments", "tasks", ["task_id"], ["id"])
    op.create_foreign_key(None, "comments", "user_accounts", ["from_user_id"], ["id"])
    op.drop_column("comments", "to_user")
    op.drop_column("comments", "from_user")
    op.alter_column("tasks", "perform_user_id", existing_type=sa.UUID(), nullable=True)
    op.create_unique_constraint(None, "tokens", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tokens", type_="unique")
    op.alter_column("tasks", "perform_user_id", existing_type=sa.UUID(), nullable=False)
    op.add_column(
        "comments",
        sa.Column("from_user", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "comments", sa.Column("to_user", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("comments_from_user_fkey"),
        "comments",
        "user_accounts",
        ["from_user"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("comments_task_id_fkey"), "comments", "comments", ["task_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("comments_to_user_fkey"), "comments", "user_accounts", ["to_user"], ["id"]
    )
    op.alter_column("comments", "text", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("comments", "to_user_id")
    op.drop_column("comments", "from_user_id")
    # ### end Alembic commands ###
