"""empty message

Revision ID: c22bd919743b
Revises: 2c807717b45b
Create Date: 2025-09-07 13:01:31.558001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c22bd919743b"
down_revision: Union[str, Sequence[str], None] = "2c807717b45b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meetings",
        sa.Column("meeting_starttime", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "meetings",
        sa.Column("meeting_endtime", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_column("meetings", "meeting_datetime")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meetings",
        sa.Column(
            "meeting_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("meetings", "meeting_endtime")
    op.drop_column("meetings", "meeting_starttime")
    # ### end Alembic commands ###
