"""empty message

Revision ID: e897b7dcd5e1
Revises: 4e3f7f8d9382
Create Date: 2025-08-30 20:40:27.430515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e897b7dcd5e1"
down_revision: Union[str, Sequence[str], None] = "4e3f7f8d9382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("meeting_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_finished", sa.Boolean(), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comments",
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("from_user", sa.Uuid(), nullable=False),
        sa.Column("to_user", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["from_user"],
            ["user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_user"],
            ["user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tokens",
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tokens_refresh_token"), "tokens", ["refresh_token"], unique=True
    )
    op.create_table(
        "user_meeting_relations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("tasks", "comments")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("comments", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_table("user_meeting_relations")
    op.drop_index(op.f("ix_tokens_refresh_token"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_table("comments")
    op.drop_table("meetings")
    # ### end Alembic commands ###
